name: dkashstore
description: "Tu estilo, tu personalidad"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages (desactivado si no se usar치)
  # firebase_core: ^2.10.0
  # firebase_auth: ^4.10.0
  # cloud_firestore: ^5.0.0

  # Go Router for navigation
  go_router: ^6.0.0

  # State management: Riverpod o Provider
  provider: ^6.0.0
  riverpod: ^2.0.0

  # Icon library
  cupertino_icons: ^1.0.8

  # Base de datos SQLite
  sqflite: ^2.0.0+4
  path_provider: ^2.0.9  # Para obtener el directorio donde guardar la base de datos

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter recommendations
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Para agregar assets (im치genes) a tu aplicaci칩n
  assets:
    - assets/images/  # Si tienes im치genes en tu proyecto, esta carpeta es un ejemplo.

  # Para agregar fuentes personalizadas
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
