name: dkashstore
description: "Tu estilo, tu personalidad"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Navegación
  go_router: ^6.0.0

  # State management
  provider: ^6.0.0
  riverpod: ^2.0.0

  # Íconos
  cupertino_icons: ^1.0.8

  # Base de datos SQLite (deshabilitado si no se usa)
  sqflite: ^2.0.0+4
  path_provider: ^2.0.9  

  # Carrusel de imágenes
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Archivos de imágenes
  assets:
    - assets/images/Dkashbasicafront.png
    - assets/images/Dkashbasicaback.png
    - assets/images/catalog1.png
    - assets/images/COMPRE_AHORA.png